apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      name: peer
  # Services without DNS entries based on IP called "headless"
  clusterIP: None
  selector:
    app: mongo