## Variant #2 - Experimental. Dig into step-by-step dependencies management waterflow
#
## Base image
#FROM alpine
#
## Install npm
#RUN apk add --update npm
#
## Install dependencies
#RUN npm install
#
## Default command
#CMD ["npm", "run"]